world: gap
update_rate: 5

# sfm algorithm configure
social_force:
  animation_factor: 5.1
  # only handle pedestrians within `people_distance`
  people_distance: 6.0
  # weights of social force model
  goal_weight: 2.0
  obstacle_weight: 10.0 # default: 80.0
  social_weight: 15
  group_gaze_weight: 3.0
  group_coh_weight: 2.0
  group_rep_weight: 1.0

# pedestrians setting
pedestrians:
  - name: human_1
    pose: 6 -1 1 0 0 0
    velocity: 0.9
    radius: 0.4
    cycle: true
    ignore:
      model_1: ground_plane
    trajectory:
      goal_point_1: 6 -1 1 0 0 0
      goal_point_2: -6 1 1 0 0 0
    # group:
    #   model_1: human_2
    #   model_2: human_3
  - name: human_2
    pose: 6 0 1 0 0 0
    velocity: 0.9
    radius: 0.4
    cycle: true
    ignore:
      model_1: ground_plane
    trajectory:
      goal_point_1: 6 0 1 0 0 0
      goal_point_2: -6 0 1 0 0 0
    # group:
    #   model_1: human_1
    #   model_2: human_3
  - name: human_3
    pose: 6 1 1 0 0 0
    velocity: 0.9
    radius: 0.4
    cycle: true
    ignore:
      model_1: ground_plane
    trajectory:
      goal_point_1: 6 1 1 0 0 0
      goal_point_2: -6 -1 1 0 0 0
    # group:
    #   model_1: human_1
    #   model_2: human_2
  - name: human_4
    pose: -6 -1 1 0 0 0
    velocity: 0.9
    radius: 0.4
    cycle: true
    ignore:
      model_1: ground_plane
    trajectory:
      goal_point_1: -6 -1 1 0 0 0
      goal_point_2: 6 1 1 0 0 0
    # group:
    #   model_1: human_5
    #   model_2: human_6
  - name: human_5
    pose: -6 0 1 0 0 0
    velocity: 0.9
    radius: 0.4
    cycle: true
    ignore:
      model_1: ground_plane
    trajectory:
      goal_point_1: -6 0 1 0 0 0
      goal_point_2: 6 0 1 0 0 0
    # group:
    #   model_1: human_4
    #   model_2: human_6
  - name: human_6
    pose: -6 1 1 0 0 0
    velocity: 0.9
    radius: 0.4
    cycle: true
    ignore:
      model_1: ground_plane
    trajectory:
      goal_point_1: -6 1 1 0 0 0
      goal_point_2: 6 -1 1 0 0 0
    # group:
    #   model_1: human_4
    #   model_2: human_5
